version: 0.2

# Optional alternate build setup

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd client
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: build
